class Rwanda
  Province = {
    'Kigali City' => {
      'Nyarugenge' => [
        'Gitega',
        'Kanyinya',
        'Kigali',
        'Kimisagara',
        'Mageragere',
        'Muhima',
        'Nyakabanda',
        'Nyamirambo',
        'Nyarugenge',
        'Rwezamenyo'
      ],
        
      'Gasabo' => [
        'Bumbogo',
        'Gatsata',
        'Gikomero',
        'Gisozi',
        'Jabana',
        'Jali',
        'Kacyiru',
        'Kimihurura',
        'Kimironko',
        'Kinyinya',
        'Ndera',
        'Nduba',
        'Remera',
        'Rusororo',
        'Rutunga'
      ],
        
      'Kicukiro' => [
        'Gahanga',
        'Gatenga',
        'Gikondo',
        'Kagarama',
        'Kanombe',
        'Kicukiro',
        'Kigarama',
        'Masaka',
        'Niboye',
        'Nyarugunga'
      ],
    },
        
    'Southern Province' => {
      'Nyanza' => [
        'Busasamana',
        'Busoro',
        'Cyabakamyi',
        'Kibirizi',
        'Kigoma',
        'Mukingo',
        'Muyira',
        'Ntyazo',
        'Nyagisozi',
        'Rwabicuma'
      ],
        
      'Gisagara' => [
        'Gikonko',
        'Gishubi',
        'Kansi',
        'Kibilizi',
        'Kigembe',
        'Mamba',
        'Muganza',
        'Mugombwa',
        'Mukindo',
        'Musha',
        'Ndora',
        'Nyanza',
        'Save'
      ],
        
      'Nyaruguru' => [
        'Busanze',
        'Cyahinda',
        'Kibeho',
        'Kivu',
        'Mata',
        'Muganza',
        'Munini',
        'Ngera',
        'Ngoma',
        'Nyabimata',
        'Nyagisozi',
        'Ruheru',
        'Ruramba',
        'Rusenge'
      ],
        
      'Huye' => [
        'Gishamvu',
        'Huye',
        'Karama',
        'Kigoma',
        'Kinazi',
        'Maraba',
        'Mbazi',
        'Mukura',
        'Ngoma',
        'Ruhashya',
        'Rusatira',
        'Rwaniro',
        'Simbi',
        'Tumba'
      ],
        
      'Nyamagabe' => [
        'Buruhukiro',
        'Cyanika',
        'Gasaka',
        'Gatare',
        'Kaduha',
        'Kamegeri',
        'Kibirizi',
        'Kibumbwe',
        'Kitabi',
        'Mbazi',
        'Mugano',
        'Musange',
        'Musebeya',
        'Mushubi',
        'Nkomane',
        'Tare',
        'Uwinkingi'
      ],
        
      'Ruhango' => [
        'Bweramana',
        'Byimana',
        'Kabagari',
        'Kinazi',
        'Kinihira',
        'Mbuye',
        'Mwendo',
        'Ntongwe',
        'Ruhango'
      ],
        
      'Muhanga' => [
        'Cyeza',
        'Kabacuzi',
        'Kibangu',
        'Kiyumba',
        'Muhanga',
        'Mushishiro',
        'Nyabinoni',
        'Nyamabuye',
        'Nyarusange',
        'Rongi',
        'Rugendabari',
        'Shyogwe'
      ],
        
      'Kamonyi' => [
        'Gacurabwenge',
        'Karama',
        'Kayenzi',
        'Kayumbu',
        'Mugina',
        'Musambira',
        'Ngamba',
        'Nyamiyaga',
        'Nyarubaka',
        'Rugalika',
        'Rukoma',
        'Runda'
      ],
    },
        
    'Western Province' => {
      'Karongi' => [
        'Bwishyura',
        'Gishari',
        'Gishyita',
        'Gitesi',
        'Mubuga',
        'Murambi',
        'Murundi',
        'Mutuntu',
        'Rubengera',
        'Rugabano',
        'Ruganda',
        'Rwankuba',
        'Twumba'
      ],
        
      'Rutsiro' => [
        'Boneza',
        'Gihango',
        'Kigeyo',
        'Kivumu',
        'Manihira',
        'Mukura',
        'Murunda',
        'Musasa',
        'Mushonyi',
        'Mushubati',
        'Nyabirasi',
        'Ruhango',
        'Rusebeya'
      ],
        
      'Rubavu' => [
        'Bugeshi',
        'Busasamana',
        'Cyanzarwe',
        'Gisenyi',
        'Kanama',
        'Kanzenze',
        'Mudende',
        'Nyakiliba',
        'Nyamyumba',
        'Nyundo',
        'Rubavu',
        'Rugerero'
      ],
        
      'Nyabihu' => [
        'Bigogwe',
        'Jenda',
        'Jomba',
        'Kabatwa',
        'Karago',
        'Kintobo',
        'Mukamira',
        'Muringa',
        'Rambura',
        'Rugera',
        'Rurembo',
        'Shyira'
      ],
        
      'Ngororero' => [
        'Bwira',
        'Gatumba',
        'Hindiro',
        'Kabaya',
        'Kageyo',
        'Kavumu',
        'Matyazo',
        'Muhanda',
        'Muhororo',
        'Ndaro',
        'Ngororero',
        'Nyange',
        'Sovu'
      ],
        
      'Rusizi' => [
        'Bugarama',
        'Butare',
        'Bweyeye',
        'Gashonga',
        'Giheke',
        'Gihundwe',
        'Gikundamvura',
        'Gitambi',
        'Kamembe',
        'Muganza',
        'Mururu',
        'Nkanka',
        'Nkombo',
        'Nkungu',
        'Nyakabuye',
        'Nyakarenzo',
        'Nzahaha',
        'Rwimbogo'
      ],
        
      'Nyamasheke' => [
        'Bushekeri',
        'Bushenge',
        'Cyato',
        'Gihombo',
        'Kagano',
        'Kanjongo',
        'Karambi',
        'Karengera',
        'Kirimbi',
        'Macuba',
        'Mahembe',
        'Nyabitekeri',
        'Rangiro',
        'Ruharambuga',
        'Shangi'
      ],
    },
        
    'Northern Province' => {
      'Rulindo' => [
        'Base',
        'Burega',
        'Bushoki',
        'Buyoga',
        'Cyinzuzi',
        'Cyungo',
        'Kinihira',
        'Kisaro',
        'Masoro',
        'Mbogo',
        'Murambi',
        'Ngoma',
        'Ntarabana',
        'Rukozo',
        'Rusiga',
        'Shyorongi',
        'Tumba'
      ],
        
      'Gakenke' => [
        'Busengo',
        'Coko',
        'Cyabingo',
        'Gakenke',
        'Gashenyi',
        'Janja',
        'Kamubuga',
        'Karambo',
        'Kivuruga',
        'Mataba',
        'Minazi',
        'Mugunga',
        'Muhondo',
        'Muyongwe',
        'Muzo',
        'Nemba',
        'Ruli',
        'Rusasa',
        'Rushashi'
      ],
        
      'Musanze' => [
        'Busogo',
        'Cyuve',
        'Gacaca',
        'Gashaki',
        'Gataraga',
        'Kimonyi',
        'Kinigi',
        'Muhoza',
        'Muko',
        'Musanze',
        'Nkotsi',
        'Nyange',
        'Remera',
        'Rwaza',
        'Shingiro'
      ],
        
      'Burera' => [
        'Bungwe',
        'Butaro',
        'Cyanika',
        'Cyeru',
        'Gahunga',
        'Gatebe',
        'Gitovu',
        'Kagogo',
        'Kinoni',
        'Kinyababa',
        'Kivuye',
        'Nemba',
        'Rugarama',
        'Rugengabari',
        'Ruhunde',
        'Rusarabuge',
        'Rwerere'
      ],
        
      'Gicumbi' => [
        'Bukure',
        'Bwisige',
        'Byumba',
        'Cyumba',
        'Giti',
        'Kageyo',
        'Kaniga',
        'Manyagiro',
        'Miyove',
        'Mukarange',
        'Muko',
        'Mutete',
        'Nyamiyaga',
        'Nyankenke',
        'Rubaya',
        'Rukomo',
        'Rushaki',
        'Rutare',
        'Ruvune',
        'Rwamiko',
        'Shangasha'
      ],
    },
        
    'Eastern Province' => {
      'Rwamagana' => [
        'Fumbwe',
        'Gahengeri',
        'Gishari',
        'Karenge',
        'Kigabiro',
        'Muhazi',
        'Munyaga',
        'Munyiginya',
        'Musha',
        'Muyumbu',
        'Mwulire',
        'Nyakariro',
        'Nzige',
        'Rubona'
      ],
        
      'Nyagatare' => [
        'Gatunda',
        'Karama',
        'Karangazi',
        'Katabagemu',
        'Kiyombe',
        'Matimba',
        'Mimuli',
        'Mukama',
        'Musheli',
        'Nyagatare',
        'Rukomo',
        'Rwempasha',
        'Rwimiyaga',
        'Tabagwe'
      ],
        
      'Gatsibo' => [
        'Gasange',
        'Gatsibo',
        'Gitoki',
        'Kabarore',
        'Kageyo',
        'Kiramuruzi',
        'Kiziguro',
        'Muhura',
        'Murambi',
        'Ngarama',
        'Nyagihanga',
        'Remera',
        'Rugarama',
        'Rwimbogo'
      ],
        
      'Kayonza' => [
        'Gahini',
        'Kabare',
        'Kabarondo',
        'Mukarange',
        'Murama',
        'Murundi',
        'Mwiri',
        'Ndego',
        'Nyamirama',
        'Rukara',
        'Ruramira',
        'Rwinkwavu'
      ],
        
      'Kirehe' => [
        'Gahara',
        'Gatore',
        'Kigarama',
        'Kigina',
        'Kirehe',
        'Mahama',
        'Mpanga',
        'Musaza',
        'Mushikiri',
        'Nasho',
        'Nyamugali',
        'Nyarubuye'
      ],
        
      'Ngoma' => [
        'Gashanda',
        'Jarama',
        'Karembo',
        'Kazo',
        'Kibungo',
        'Mugesera',
        'Murama',
        'Mutenderi',
        'Remera',
        'Rukira',
        'Rukumberi',
        'Rurenge',
        'Sake',
        'Zaza'
      ],
        
      'Bugesera' => [
        'Gashora',
        'Juru',
        'Kamabuye',
        'Mareba',
        'Mayange',
        'Musenyi',
        'Mwogo',
        'Ngeruka',
        'Ntarama',
        'Nyamata',
        'Nyarugenge',
        'Rilima',
        'Ruhuha',
        'Rweru',
        'Shyara'
      ],
    }
  }
end

